-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('login_pb')


local localTable = {}
LOGINACCOUNT = protobuf.Descriptor()
localTable.LOGINACCOUNT_ACCOUNT_FIELD = protobuf.FieldDescriptor()
localTable.LOGINACCOUNT_PASSWORD_FIELD = protobuf.FieldDescriptor()


localTable.LOGINACCOUNT_ACCOUNT_FIELD.name = "account"
localTable.LOGINACCOUNT_ACCOUNT_FIELD.full_name = ".login.LoginAccount.account"
localTable.LOGINACCOUNT_ACCOUNT_FIELD.number = 1
localTable.LOGINACCOUNT_ACCOUNT_FIELD.index = 0
localTable.LOGINACCOUNT_ACCOUNT_FIELD.label = 2
localTable.LOGINACCOUNT_ACCOUNT_FIELD.has_default_value = false
localTable.LOGINACCOUNT_ACCOUNT_FIELD.default_value = ""
localTable.LOGINACCOUNT_ACCOUNT_FIELD.type = 9
localTable.LOGINACCOUNT_ACCOUNT_FIELD.cpp_type = 9

localTable.LOGINACCOUNT_PASSWORD_FIELD.name = "password"
localTable.LOGINACCOUNT_PASSWORD_FIELD.full_name = ".login.LoginAccount.password"
localTable.LOGINACCOUNT_PASSWORD_FIELD.number = 2
localTable.LOGINACCOUNT_PASSWORD_FIELD.index = 1
localTable.LOGINACCOUNT_PASSWORD_FIELD.label = 2
localTable.LOGINACCOUNT_PASSWORD_FIELD.has_default_value = false
localTable.LOGINACCOUNT_PASSWORD_FIELD.default_value = ""
localTable.LOGINACCOUNT_PASSWORD_FIELD.type = 9
localTable.LOGINACCOUNT_PASSWORD_FIELD.cpp_type = 9

LOGINACCOUNT.name = "LoginAccount"
LOGINACCOUNT.full_name = ".login.LoginAccount"
LOGINACCOUNT.nested_types = {}
LOGINACCOUNT.enum_types = {}
LOGINACCOUNT.fields = {localTable.LOGINACCOUNT_ACCOUNT_FIELD, localTable.LOGINACCOUNT_PASSWORD_FIELD}
LOGINACCOUNT.is_extendable = false
LOGINACCOUNT.extensions = {}

LoginAccount = protobuf.Message(LOGINACCOUNT)

